name: Incident Documentation Workflow

on:
  workflow_dispatch:
    inputs:
      issueType:
        description: 'Type of Issue (e.g., Performance, Security)'
        required: true
        default: 'Performance'
      issueDescription:
        description: 'Description of the Issue'
        required: true
        default: 'Performance degradation detected in the payment processing module.'

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest
    outputs:
      jiraTicketId: ${{ steps.create_ticket.outputs.jiraTicketId }}
    steps:
      - name: Create Jira Ticket
        id: create_ticket
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        run: |
          RESPONSE=$(curl --request POST \
            --url "${JIRA_BASE_URL}/rest/api/3/issue" \
            --user "${JIRA_USER_EMAIL}:${JIRA_API_TOKEN}" \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data '{
              "fields": {
                "project": { "key": "ANOMALIES" },
                "summary": "${{ github.event.inputs.issueType }}",
                "description": {
                  "type": "doc",
                  "version": 1,
                  "content": [
                    {
                      "type": "paragraph",
                      "content": [
                        { "type": "text", "text": "${{ github.event.inputs.issueDescription }}" }
                      ]
                    }
                  ]
                },
                "issuetype": { "name": "Task" }
              }
            }')
          echo "$RESPONSE"
          JIRA_TICKET_ID=$(echo $RESPONSE | jq -r '.id')
          echo "::set-output name=jiraTicketId::$JIRA_TICKET_ID"

  create-confluence-page:
    needs: create-jira-ticket
    runs-on: ubuntu-latest
    steps:
      - name: Create Confluence Page with Variables
        env:
          CONFLUENCE_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          CONFLUENCE_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          CONFLUENCE_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        run: |
          JIRA_TICKET_ID="${{ needs.create-jira-ticket.outputs.jiraTicketId }}"
          # Define the document variables
          ANOMALY_TITLE="Simulated Anomaly ${JIRA_TICKET_ID}"
          DATE=$(date +'%Y-%m-%d')
          VERSION_NUMBER="1.0"
          DETECTION_SOURCE="Simulated New Relic Alert"
          ISSUE_DESCRIPTION="This is a simulated description based on New Relic data."

          # Prepare the content with variables included
          PAGE_CONTENT="<h2>Anomaly Title: ${ANOMALY_TITLE}</h2>
                        <p>Date: ${DATE}</p>
                        <p>Version Number: ${VERSION_NUMBER}</p>
                        <p>Detection Source: ${DETECTION_SOURCE}</p>
                        <p>Issue Description: ${ISSUE_DESCRIPTION}</p>"

          JSON_PAYLOAD=$(jq -n \
                            --arg title "Risk Management Report #$JIRA_TICKET_ID" \
                            --arg content "$PAGE_CONTENT" \
                            '{ "type": "page", "title": $title, "space": {"key": "SD"}, "ancestors": [{"id": "229625"}], "body": { "storage": { "value": $content, "representation": "storage" } } }')

          curl --request POST \
            --url "$CONFLUENCE_BASE_URL/wiki/rest/api/content/" \
            --user "$CONFLUENCE_USER_EMAIL:$CONFLUENCE_API_TOKEN" \
            --header 'Content-Type: application/json' \
            --data "$JSON_PAYLOAD" \
            --fail --silent --show-error
